"""Notamify SDK for Python."""

from .client import APIError, NotamifyClient
from .cloudflared import CloudflaredError, CloudflaredManager
from .config import ConfigStore, SDKConfig
from .models import (
    ActiveNotamsQuery,
    AircraftDetails,
    BriefingJobCreated,
    BriefingJobStatusDTO,
    BriefingResponse,
    BriefingStatus,
    CriticalOperationalRestrictionGroup,
    GenerateFlightBriefingRequest,
    GenerateFlightBriefingResponse,
    HistoricalNotamsQuery,
    Listener,
    ListenerAffectedElementFilter,
    ListenerFilters,
    ListenerMetadata,
    ListenerMode,
    ListenerRequest,
    ListenerTimeWindowFilter,
    LocationType,
    LocationWithType,
    NearbyNotamsQuery,
    NotamDTO,
    NotamInterpretationDTO,
    NotamListResult,
    NotamMapElementDTO,
    NotamPrioritisationRequest,
    NotamPrioritisationResult,
    NotamPriority,
    NotamScheduleInterpretationDTO,
    PrioritizedNotamDTO,
    SandboxDeliveryResult,
    WatcherWebhookEvent,
    WebhookContext,
    WebhookLifecycleChange,
    WebhookLocationCoordinates,
    WebhookLocationContext,
    WebhookMessageKind,
    WebhookLog,
    WebhookLogsResponse,
)
from .receiver import ReceiverConfig, ReceivedEvent, WebhookReceiver
from .signature import SignatureVerificationError, verify_signature

__all__ = [
    "APIError",
    "ActiveNotamsQuery",
    "AircraftDetails",
    "BriefingJobCreated",
    "BriefingJobStatusDTO",
    "BriefingResponse",
    "BriefingStatus",
    "CloudflaredError",
    "CloudflaredManager",
    "ConfigStore",
    "CriticalOperationalRestrictionGroup",
    "GenerateFlightBriefingRequest",
    "GenerateFlightBriefingResponse",
    "HistoricalNotamsQuery",
    "Listener",
    "ListenerAffectedElementFilter",
    "ListenerFilters",
    "ListenerMetadata",
    "ListenerMode",
    "ListenerRequest",
    "ListenerTimeWindowFilter",
    "LocationType",
    "LocationWithType",
    "NearbyNotamsQuery",
    "NotamDTO",
    "NotamInterpretationDTO",
    "NotamListResult",
    "NotamMapElementDTO",
    "NotamPrioritisationRequest",
    "NotamPrioritisationResult",
    "NotamPriority",
    "NotamScheduleInterpretationDTO",
    "NotamifyClient",
    "PrioritizedNotamDTO",
    "ReceiverConfig",
    "ReceivedEvent",
    "SandboxDeliveryResult",
    "SDKConfig",
    "SignatureVerificationError",
    "WatcherWebhookEvent",
    "WebhookContext",
    "WebhookLifecycleChange",
    "WebhookLocationCoordinates",
    "WebhookLog",
    "WebhookLocationContext",
    "WebhookMessageKind",
    "WebhookLogsResponse",
    "WebhookReceiver",
    "verify_signature",
]
